# Travis CI test file to test Golang-Cover project

sudo: required
before_install:
  - sudo apt-get -y install texlive-full
  - sudo add-apt-repository -y ppa:gophers/archive
  - sudo apt-get -y update
  - sudo apt-get -y install golang-1.10-go

# # Enable Golang support
# language: go
#
# # Compiler selection
# go:
#   - 1.10.1
#   - master

# Build steps
script:
  - go get gopkg.in/gomail.v2
  - go build main.go
