# Travis CI test file to test Golang-Cover project

sudo: required
before_install:
  - sudo apt-get -y install texlive-full
  - sudo add-apt-repository -y ppa:gophers/archive
  - sudo apt-get -y update
  - sudo apt-get -y install golang-1.10-go
  - go get gopkg.in/gomail.v2


# Build steps
script:
  - go build main.go
  - ./main --opt 8 --company "test inc"
